### ISSUE TITLE
Revisar el código generado.

### ISSUE THREAD

**Issue by FabianRoSan** [AdrianaGlez94/PHP-practic-SKILLS_UP#1]
Se detectan varios fallos en la estructura del código. Etiquetas sin cerrar, atributos sin asignar correctamente, etiquetas anidadas en sitios que no le corresponden... 

Intenta organizar mejor el código para que se más legible y no tener tanto aire entre lineas y bloques de secciones, dificulta saber que parte del código se está leyendo.

**Comment by AdrianaGlez94** [comment]
luego me dices si lo terminé de corregir
